### ISSUE TITLE
[Tutorials > Hello minikube] Korean Translation.

### ISSUE THREAD

**Issue by claudiajkang** [k8s-kr/website#2]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
[Tutorials > Hello Minikube](https://kubernetes.io/docs/tutorials/hello-minikube) page does't have translation of korean.

**Proposed Solution:**
Translate to korean about [this page](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/hello-minikube.md). 
- **Translation list**
    - [ ] [hello-minikube](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/hello-minikube.md) 

**Page to Update:**
https://github.com/k8s-kr/website/content/ko/docs/tutorials/hello-minikube.md

**Comment by gochist** [comment]
duplicated with https://github.com/kubernetes/kubernetes-docs-ko/issues/5
