### ISSUE TITLE
[Tutorials > Kubernetes Basics] Korean Translation.

### ISSUE THREAD

**Issue by claudiajkang** [k8s-kr/website#3]
**This is a...** 

- [X] Feature Request
- [ ] Bug Report

**Problem:**
[Tutorials > Kubernetes Basics](https://kubernetes.io/docs/tutorials/kubernetes-basics) page does't have translation of korean.

**Proposed Solution:**
Translate to korean about [this folder](https://github.com/k8s-kr/website/tree/master/content/en/docs/tutorials/kubernetes-basics). 
- **Translation list**
    - [ ] [Overview](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/kubernetes-basics/index.html) 
    - [ ] [Create a Cluster](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html) 
    - [ ] [Deploy an App](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html) 
    - [ ] [Explore Your App](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html) 
    - [ ] [Expose Your App Publicly](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html) 
    - [ ] [Scale Your App](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/kubernetes-basics/scale/scale-intro.html) 
    - [ ] [Update Your App](https://github.com/k8s-kr/website/blob/master/content/en/docs/tutorials/kubernetes-basics/update/update-intro.html) 
 
**Page to Update:**
https://github.com/k8s-kr/website/tree/master/content/ko/docs/tutorials/kubernetes-basics

**Comment by gochist** [comment]
duplicated with https://github.com/kubernetes/kubernetes-docs-ko/issues/6
